src/Games.jl
src/normal_form_game.jl
test/runtests.jl
test/test_normal_form_game.jl

This is simply the PR from QuantEcon/QuantEcon.jl#95 moved here for further work. See that issue for discussion so far.

added files from qe.jl PR

---

test/REQUIRE
test/test_pure_nash.jl

Add some games in "test_pure_nash.jl".
1. Matching Pennies Game with 0 Pure Action Nash equilibrium;
2. Coordination game with 2 Pure Action Nash equilibria;
3. Unanimity Game with more than two players.
In the Unanimity Game, I use `combinations` from `Combinatorics`, and thus `Combinatorics` is required.

Add some complicated games for testing "pure_nash".

---

.travis.yml
src/normal_form_game.jl
test/test_normal_form_game.jl

Fix https://github.com/QuantEcon/Games.jl/issues/2#issuecomment-197400877 by https://github.com/QuantEcon/Games.jl/issues/28#issue-215032337.

Resolve type instability in NormalFormGame(::Matrix)

---

.travis.yml
src/Games.jl
src/normal_form_game.jl
test/runtests.jl
test/test_normal_form_game.jl

Remove 0.4 compatibility code

---

.travis.yml
README.md

Will see if docs are deployed.

Add docs badge

---

.travis.yml
REQUIRE
docs/make.jl
src/Games.jl
src/normal_form_game.jl
src/pure_nash.jl
src/repeated_game.jl
src/repeated_game_util.jl
test/test_normal_form_game.jl
test/test_repeated_game.jl

Fix 0.6 deprecations

---

src/normal_form_game.jl
test/test_normal_form_game.jl

NormalFormGame: Add getindex and setindex! for CartesianIndex

---

src/Games.jl
src/random.jl
test/test_random.jl

Replaced MvNormal with MVNSampler in random.jl, added an option to choose RNG, and added a test for the corner values of rho.
Close #35

Use mvn sampler

---

src/normal_form_game.jl

Given the change in [Base.showarray](https://github.com/JuliaLang/julia/blob/5645fb212b90910b06c5a06f08c746fdd5b82f80/base/show.jl#L1838).
Currently:
```jl
julia> Player([3 1; 0 2])
2×2 Player{2,Int64}:
[3 1; 0 2]
```
By this PR:
```jl
julia> Player([3 1; 0 2])
2×2 Player{2,Int64}:
3  1
0  2
```

Update Base.show(::IO, ::Player)

---

.travis.yml

This reverts commit b34045f21f7ba25d3f3fd57aa5c7889f4f66a985.

Revert "Clone NLopt on master"

---

docs/README.md
docs/Structure
docs/src/index.md
src/Games.jl
src/normal_form_game.jl
src/random.jl
src/repeated_game.jl

Let's work in this branch for further fixes.

Further fixes in docstrings

---

src/repeated_game.jl

Adds an option to choose an LP solver for repeated_game.jl
Close #58

FEAT: Add option to choose LP solver to repeated_game.jl

---

docs/README.md
docs/auto_doc_gen.jl
src/normal_form_game.jl
src/pure_nash.jl
src/repeated_game.jl
src/support_enumeration.jl

In `repeated_game.jl`:
```
- `C::Vector{Float64}` : ... of length `nH` ...
- `H::Matrix{Float64}` : ... of shape (or size?) `(nH, 2)` ...
```

DOC: Further edits

---

src/repeated_game.jl
test/test_repeated_game.jl

Partially address type instability of outerapproximation

---

.travis.yml
REQUIRE
benchmark/benchmarks.jl
docs/Structure
src/Games.jl
src/generators/Generators.jl
src/generators/bimatrix_generators.jl
test/generators/runtests.jl
test/generators/test_bimatrix_generators.jl
test/runtests.jl

Close #53. Julia version of QuantEcon/QuantEcon.py#392.

Add sample game generators from bimatrix-generators

---

REQUIRE
src/repeated_game.jl

FIX: Update outerapproximation for latest Polyhedra

---

.travis.yml
REQUIRE
src/Games.jl
src/generators/Generators.jl
src/generators/bimatrix_generators.jl
src/normal_form_game.jl
src/pure_nash.jl
src/random.jl
src/repeated_game.jl
src/support_enumeration.jl
test/generators/test_bimatrix_generators.jl
test/runtests.jl
test/test_normal_form_game.jl
test/test_random.jl

(Some tests still fail for 0.7.)

0.7 compat

---

src/repeated_game.jl

See https://github.com/JuliaPolyhedra/Polyhedra.jl/issues/118#issuecomment-423800316

Update for `default_library`

---

docs/auto_doc_gen.jl

Fix deprecation of `auto_doc_gen`

---

.travis.yml
REQUIRE
docs/auto_doc_gen.jl
src/Games.jl
src/generators/Generators.jl
src/normal_form_game.jl
src/repeated_game.jl
src/support_enumeration.jl
test/generators/test_bimatrix_generators.jl
test/runtests.jl
test/test_random.jl

Require Julia 0.7

---

src/Games.jl
src/normal_form_game.jl
test/test_normal_form_game.jl

I added `delete_action` function for `Player` and `NormalFormGame` instances in normal_form_game.jl
Also, add the test code of this function in test_normal_form_game.jl, and fix Games.jl
Close(#96)

FEAT: Add `delete_action`

---

src/normal_form_game.jl
test/test_normal_form_game.jl

API: Change `tie_breaking` to `Symbol`

---

REQUIRE
src/Games.jl
src/normal_form_game.jl
src/pure_nash.jl
test/test_normal_form_game.jl

- Add `rng` to `best_response`
- Allow `tol` to be any `Real`

Add `BROptions`

---

src/repeated_game.jl
test/test_repeated_game.jl

Use `MathOptInterface` in place of `MathProgBase` in repeated_game.jl

---

src/normal_form_game.jl
src/random.jl
src/repeated_game.jl
src/support_enumeration.jl

Remove authors' name from
- normal_form_game.jl
- random.jl
- repeated_game.jl
- support_enumeration.jl

Remove authors' name

---

.travis.yml
Project.toml
REQUIRE

closes #119 
1. Generates `Project.toml` by [`gen_project.jl`](https://github.com/JuliaLang/Pkg.jl/blob/934f8b71eb436da6d2bdb30ccfc80e5e11891c5b/bin/gen_project.jl).
2. Add repo info.
3. Delete `REQUIRE`.

Introduce `Project.toml`.

---

Project.toml

Following [Clp.jl](https://github.com/JuliaOpt/Clp.jl/blob/85ed54d54bc3229b98821c9281a7162050726d03/Project.toml#L16).

Add MOI version lower bound

---

src/Games.jl
src/normal_form_game.jl
src/repeated_game.jl
src/util.jl
test/test_normal_form_game.jl

Cf. jump-dev/MathOptInterface.jl#1206

FIX: Fix Clp deprecation warning

---

.github/workflows/ci.yml
Project.toml
docs/Structure
src/Games.jl
src/lrsnash.jl
test/runtests.jl
test/test_lrsnash.jl

Call `solve_nash` from [`LRSLib.jl`](https://github.com/JuliaPolyhedra/LRSLib.jl).

EHN: Add `lrsnash`

---

src/GameTheory.jl
src/normal_form_game.jl
test/test_normal_form_game.jl

Close #7
```julia
julia> g = NormalFormGame(randn(3, 2, 2))
3×2 NormalFormGame{2, Float64}
julia> print(g)
3×2 NormalFormGame{2, Float64}:
[1.00783, -0.217958]  [0.888136, -1.82716]
[0.759667, 0.945713]  [0.217776, -0.718575]
[-0.224237, 0.42577]  [-0.338728, 0.679999]
julia> g.players[1]
3×2 Player{2, Float64}:
1.00783    0.888136
0.759667   0.217776
-0.224237  -0.338728
julia> g.players[2]
2×3 Player{2, Float64}:
-0.217958   0.945713  0.42577
-1.82716   -0.718575  0.679999
```

EHN: Add payoff_profile_array

---

Project.toml
src/GameTheory.jl
src/repeated_game.jl
test/test_repeated_game.jl

Add `CDDLib.jl` as a (non-extra) dependency

RFC: repeated_game: Change the default `plib` to `CDDLib.library()`

---

src/random.jl
test/test_random.jl

For the set to draw payoffs from

EHN: random_game: Add type or range argument

---

docs/README.md
docs/Structure

Introduce "Learning Algorithms" category

DOC: Update Structure

---

src/support_enumeration.jl

Detected by analysis with ChatGPT 01 pro.
(But has almost zero impact, given the brute-force nature of the support enumeration algorithm.)

RFC: support_enumeration: Reduce intermediate array creation
